title:
description:
theme: minima
footer:
  text: "© 2023 Adrian Herscu"
  links:
    - text: "GitHub"
      url: "http://kuku"

github_username:  QA-Automation-Starter
linkedin_username: adrianherscu

header_pages: []